using MediatR;
using Microsoft.EntityFrameworkCore;
using ResumeBuilder.Application.Common.Interfaces;
using ResumeBuilder.Application.Features.Resumes.DTOs;
using ResumeBuilder.Domain.Exceptions;
namespace ResumeBuilder.Application.Features.Resumes.Queries.GetResumeById;
public class GetResumeByIdQueryHandler : IRequestHandler<GetResumeByIdQuery, ResumeDetailDto>
{
    private readonly IApplicationDbContext _ctx;
    public GetResumeByIdQueryHandler(IApplicationDbContext ctx) => _ctx = ctx;
    public async Task<ResumeDetailDto> Handle(GetResumeByIdQuery r, CancellationToken ct)
    {
        var resume = await _ctx.Resumes.Include(x => x.Educations.Where(e => !e.IsDeleted)).Include(x => x.Experiences.Where(e => !e.IsDeleted)).Include(x => x.ResumeSkills).ThenInclude(rs => rs.Skill).Include(x => x.Projects.Where(p => !p.IsDeleted)).Include(x => x.ResumeLanguages).ThenInclude(rl => rl.Language).Include(x => x.Certificates.Where(c => !c.IsDeleted)).Include(x => x.Template).FirstOrDefaultAsync(x => x.Id == r.ResumeId && !x.IsDeleted, ct) ?? throw new NotFoundException("Resume", r.ResumeId);
        if (r.RequestingUserId.HasValue && resume.UserId != r.RequestingUserId && !resume.IsPublic) throw new ForbiddenAccessException();
        return new ResumeDetailDto { Id = resume.Id, Title = resume.Title, Summary = resume.Summary, JobTitle = resume.JobTitle, Status = resume.Status.ToString(), IsPublic = resume.IsPublic, PublicSlug = resume.PublicSlug, ViewCount = resume.ViewCount, UserId = resume.UserId, TemplateId = resume.TemplateId, TemplateName = resume.Template?.Name, Phone = resume.Phone, Email = resume.Email, Address = resume.Address, City = resume.City, Country = resume.Country, PostalCode = resume.PostalCode, Website = resume.Website, LinkedIn = resume.LinkedIn, GitHub = resume.GitHub, ProfilePicture = resume.ProfilePicture, CreatedAt = resume.CreatedAt, UpdatedAt = resume.UpdatedAt, Educations = resume.Educations.OrderBy(e => e.SortOrder).Select(e => new EducationDto { Id = e.Id, SchoolName = e.SchoolName, Degree = e.Degree, FieldOfStudy = e.FieldOfStudy, Location = e.Location, StartDate = e.StartDate, EndDate = e.EndDate, IsCurrentlyStudying = e.IsCurrentlyStudying, Grade = e.Grade, Description = e.Description, SortOrder = e.SortOrder }).ToList(), Experiences = resume.Experiences.OrderBy(e => e.SortOrder).Select(e => new ExperienceDto { Id = e.Id, CompanyName = e.CompanyName, JobTitle = e.JobTitle, Location = e.Location, EmploymentType = e.EmploymentType, StartDate = e.StartDate, EndDate = e.EndDate, IsCurrentJob = e.IsCurrentJob, Description = e.Description, SortOrder = e.SortOrder }).ToList(), Skills = resume.ResumeSkills.OrderBy(rs => rs.SortOrder).Select(rs => new ResumeSkillDto { Id = rs.Id, SkillId = rs.SkillId, SkillName = rs.Skill.Name, Category = rs.Skill.Category, Level = rs.Level.ToString(), SortOrder = rs.SortOrder }).ToList(), Projects = resume.Projects.OrderBy(p => p.SortOrder).Select(p => new ProjectDto { Id = p.Id, Name = p.Name, Description = p.Description, Technologies = p.Technologies, Url = p.Url, GithubUrl = p.GithubUrl, StartDate = p.StartDate, EndDate = p.EndDate, IsOngoing = p.IsOngoing, SortOrder = p.SortOrder }).ToList(), Languages = resume.ResumeLanguages.OrderBy(rl => rl.SortOrder).Select(rl => new ResumeLanguageDto { Id = rl.Id, LanguageId = rl.LanguageId, LanguageName = rl.Language.Name, Level = rl.Level.ToString(), SortOrder = rl.SortOrder }).ToList(), Certificates = resume.Certificates.OrderBy(c => c.SortOrder).Select(c => new CertificateDto { Id = c.Id, Name = c.Name, IssuingOrganization = c.IssuingOrganization, IssueDate = c.IssueDate, ExpirationDate = c.ExpirationDate, DoesNotExpire = c.DoesNotExpire, CredentialId = c.CredentialId, CredentialUrl = c.CredentialUrl, SortOrder = c.SortOrder }).ToList() };
    }
}
