using ResumeBuilder.Domain.Enums;
namespace ResumeBuilder.Application.Features.Resumes.DTOs;
public class ResumeListDto { public Guid Id { get; set; } public string Title { get; set; } = ""; public string? JobTitle { get; set; } public string Status { get; set; } = ""; public bool IsPublic { get; set; } public string? PublicSlug { get; set; } public int ViewCount { get; set; } public string? TemplateName { get; set; } public DateTime CreatedAt { get; set; } public DateTime? UpdatedAt { get; set; } }
public class ResumeDetailDto { public Guid Id { get; set; } public string Title { get; set; } = ""; public string? Summary { get; set; } public string? JobTitle { get; set; } public string Status { get; set; } = ""; public bool IsPublic { get; set; } public string? PublicSlug { get; set; } public int ViewCount { get; set; } public Guid UserId { get; set; } public Guid? TemplateId { get; set; } public string? TemplateName { get; set; } public string? Phone { get; set; } public string? Email { get; set; } public string? Address { get; set; } public string? City { get; set; } public string? Country { get; set; } public string? PostalCode { get; set; } public string? Website { get; set; } public string? LinkedIn { get; set; } public string? GitHub { get; set; } public string? ProfilePicture { get; set; } public DateTime CreatedAt { get; set; } public DateTime? UpdatedAt { get; set; } public List<EducationDto> Educations { get; set; } = new(); public List<ExperienceDto> Experiences { get; set; } = new(); public List<ResumeSkillDto> Skills { get; set; } = new(); public List<ProjectDto> Projects { get; set; } = new(); public List<ResumeLanguageDto> Languages { get; set; } = new(); public List<CertificateDto> Certificates { get; set; } = new(); }
public class CreateResumeDto { public string Title { get; set; } = ""; public string? Summary { get; set; } public string? JobTitle { get; set; } public Guid? TemplateId { get; set; } public string? Phone { get; set; } public string? Email { get; set; } public string? Address { get; set; } public string? City { get; set; } public string? Country { get; set; } public string? PostalCode { get; set; } public string? Website { get; set; } public string? LinkedIn { get; set; } public string? GitHub { get; set; } }
public class UpdateResumeDto : CreateResumeDto { }
public class EducationDto { public Guid Id { get; set; } public string SchoolName { get; set; } = ""; public string Degree { get; set; } = ""; public string? FieldOfStudy { get; set; } public string? Location { get; set; } public DateTime StartDate { get; set; } public DateTime? EndDate { get; set; } public bool IsCurrentlyStudying { get; set; } public string? Grade { get; set; } public string? Description { get; set; } public int SortOrder { get; set; } }
public class CreateEducationDto { public string SchoolName { get; set; } = ""; public string Degree { get; set; } = ""; public string? FieldOfStudy { get; set; } public string? Location { get; set; } public DateTime StartDate { get; set; } public DateTime? EndDate { get; set; } public bool IsCurrentlyStudying { get; set; } public string? Grade { get; set; } public string? Description { get; set; } public int SortOrder { get; set; } }
public class ExperienceDto { public Guid Id { get; set; } public string CompanyName { get; set; } = ""; public string JobTitle { get; set; } = ""; public string? Location { get; set; } public string? EmploymentType { get; set; } public DateTime StartDate { get; set; } public DateTime? EndDate { get; set; } public bool IsCurrentJob { get; set; } public string? Description { get; set; } public int SortOrder { get; set; } }
public class CreateExperienceDto { public string CompanyName { get; set; } = ""; public string JobTitle { get; set; } = ""; public string? Location { get; set; } public string? EmploymentType { get; set; } public DateTime StartDate { get; set; } public DateTime? EndDate { get; set; } public bool IsCurrentJob { get; set; } public string? Description { get; set; } public int SortOrder { get; set; } }
public class ResumeSkillDto { public Guid Id { get; set; } public Guid SkillId { get; set; } public string SkillName { get; set; } = ""; public string? Category { get; set; } public string Level { get; set; } = ""; public int SortOrder { get; set; } }
public class AddSkillToResumeDto { public Guid SkillId { get; set; } public SkillLevel Level { get; set; } = SkillLevel.Intermediate; public int SortOrder { get; set; } }
public class ProjectDto { public Guid Id { get; set; } public string Name { get; set; } = ""; public string? Description { get; set; } public string? Technologies { get; set; } public string? Url { get; set; } public string? GithubUrl { get; set; } public DateTime? StartDate { get; set; } public DateTime? EndDate { get; set; } public bool IsOngoing { get; set; } public int SortOrder { get; set; } }
public class CreateProjectDto { public string Name { get; set; } = ""; public string? Description { get; set; } public string? Technologies { get; set; } public string? Url { get; set; } public string? GithubUrl { get; set; } public DateTime? StartDate { get; set; } public DateTime? EndDate { get; set; } public bool IsOngoing { get; set; } public int SortOrder { get; set; } }
public class ResumeLanguageDto { public Guid Id { get; set; } public Guid LanguageId { get; set; } public string LanguageName { get; set; } = ""; public string Level { get; set; } = ""; public int SortOrder { get; set; } }
public class AddLanguageToResumeDto { public Guid LanguageId { get; set; } public LanguageLevel Level { get; set; } = LanguageLevel.B1; public int SortOrder { get; set; } }
public class CertificateDto { public Guid Id { get; set; } public string Name { get; set; } = ""; public string? IssuingOrganization { get; set; } public DateTime? IssueDate { get; set; } public DateTime? ExpirationDate { get; set; } public bool DoesNotExpire { get; set; } public string? CredentialId { get; set; } public string? CredentialUrl { get; set; } public int SortOrder { get; set; } }
public class CreateCertificateDto { public string Name { get; set; } = ""; public string? IssuingOrganization { get; set; } public DateTime? IssueDate { get; set; } public DateTime? ExpirationDate { get; set; } public bool DoesNotExpire { get; set; } public string? CredentialId { get; set; } public string? CredentialUrl { get; set; } public int SortOrder { get; set; } }
